import { colors } from 'styles/constants/colors';

const lightTheme = {
  primary: colors.EVERGLADE,
  secondary: colors.BLUE_ROMANCE,
  danger: colors.ALIZARIN_CRIMSON,
  warning: colors.RAJAH,
  warningOpacity: 'rgba(248, 185, 102, 0.8)',
  text: colors.MINE_SHAFT,
  textOpposition: colors.WHITE,
  textActive: colors.GREEN_HAZE,
  textInProgress: colors.TANGERINE,
  textReady: colors.CERULEAN,
  textContrast: colors.SILVER3,

  placeholder: colors.SUVA_GRAY,
  bsPlacehodler: colors.PALE_SKY,
  separating: colors.ALTO,
  separatingOpacity: 'rgba(216, 216, 216, 0.5)',
  textBlur: colors.SILVER,
  borderQuantity: colors.MERCURY,
  borderSelect: colors.SILVER,
  borderSelected: colors.PASTEL_GREEN,
  textSecondary: 'rgba(58,52,51,0.7)',
  background: colors.WHITE,
  backgroundVariant: colors.DODGER_BLUE,
  contrastBackground: colors.ATHENS_GRAY,
  backBackground: colors.WHITE_SMOKE,
  buttonBackgroundVariant: colors.ALABASTER,
  backgroundSelected: colors.BLACK_SMOKE,
  statusBadgeNew: colors.GALLERY,
  statusBadgeInProgress: colors.SERENADE,
  statusBadgeCompleted: colors.HINT_OF_GREEN,
  statusBadgeReady: colors.BUBBLES,
  statusBadgeCancel: colors.FAIR_PINK,
  iconBorder: colors.CORN,
  iconColor: colors.BRIGHT_SUN,
  border: 'rgba(58,52,51,0.12)',
  borderLight: 'rgba(224,224,224)',
  fontFamily: "'Roboto', Helvetica, Arial, sans-serif",
  backgroundLowOpacityTable: 'rgba(255, 255, 255, 0.5)',
  tableBorder: colors.SILVER2,
};

const darkTheme: Theme = {
  primary: colors.EVERGLADE,
  secondary: colors.BLUE_ROMANCE,
  danger: colors.ALIZARIN_CRIMSON,
  warning: colors.RAJAH,
  warningOpacity: 'rgba(248, 185, 102, 0.8)',
  text: colors.MINE_SHAFT,
  textOpposition: colors.WHITE,
  textActive: colors.GREEN_HAZE,
  textInProgress: colors.TANGERINE,
  textReady: colors.CERULEAN,
  textBlur: colors.SILVER,
  textContrast: colors.SILVER3,
  placeholder: colors.SUVA_GRAY,
  bsPlacehodler: colors.PALE_SKY,
  separating: colors.ALTO,
  separatingOpacity: 'rgba(216, 216, 216, 0.5)',
  borderQuantity: colors.MERCURY,
  borderSelect: colors.SILVER,
  borderSelected: colors.PASTEL_GREEN,
  textSecondary: 'rgba(241,233,231,0.6)',
  background: colors.WHITE,
  backgroundVariant: colors.DODGER_BLUE,
  backgroundSelected: colors.BLACK_SMOKE,

  contrastBackground: colors.ATHENS_GRAY,
  backBackground: colors.WHITE_SMOKE,
  buttonBackgroundVariant: colors.ALABASTER,
  statusBadgeNew: colors.GALLERY,
  statusBadgeInProgress: colors.SERENADE,
  statusBadgeCompleted: colors.HINT_OF_GREEN,
  statusBadgeReady: colors.BUBBLES,
  statusBadgeCancel: colors.FAIR_PINK,
  iconBorder: colors.CORN,
  iconColor: colors.BRIGHT_SUN,
  border: 'rgba(241,233,231,0.15)',
  borderLight: 'rgba(224,224,224)',
  fontFamily: "'Roboto', Helvetica, Arial, sans-serif",
  backgroundLowOpacityTable: 'rgba(255, 255, 255, 0.5)',
  tableBorder: colors.SILVER2,
};

export type Theme = typeof lightTheme;

export const themes = {
  light: lightTheme,
  dark: darkTheme,
};
